#!/bin/sh
#
# Simple script for setting up an iFit distribution package.
#
#   This file is part of the iFit package
#   Copyright (C) 2010, All rights reserved
#   Institut Laue Langevin, Grenoble, France
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; version 2 of the License.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# Version: $Revision: 1.5 $
# define version and symbols that will be replaced in many places
IFIT_TARNAME=ifit
IFIT_NAME=iFit
IFIT_VERSION=$1
MONTH=`date +"%b"`
DAY=`date +"%d"`
YEAR=`date +"%Y"`
IFIT_DATE="$MONTH. $DAY, $YEAR"
IFIT_STRING="$IFIT_NAME $IFIT_VERSION - $MONTH. $DAY, $YEAR"

# Create temporary workdir:
PW=`pwd`
TMPDIR=$PWD/..
DIST=$TMPDIR/$IFIT_TARNAME-$IFIT_VERSION

# Copy current PW checkout to DIST
cp -rp $PW $DIST

# Go in DIST, clean up CVS/SVN information
cd $DIST
echo "Clean up CVS/SVN info and temporary files"
find . -name CVS -exec rm -rf \{\} \; 2> /dev/null
find . -name .CVS -exec rm -rf \{\} \; 2> /dev/null
find . -name CVSROOT -exec rm -rf \{\} \; 2> /dev/null
find . -name svn -exec rm -rf \{\} \; 2> /dev/null
find . -name .svn -exec rm -rf \{\} \; 2> /dev/null
find . -name "*~" -exec rm -rf \{\} \; 2> /dev/null
rm mkdist
# we keep the MeX files as some users may not hace C compilers installed (e.g. Windows 64 bit)
# rm Loaders/looktxt.mex*

# Update version and date
for file in README.txt Objects/@iData/version.m Docs/index.html Docs/Install.html Applications/GUI/standalone/deb/control Applications/GUI/standalone/deb/debcreate
do
sed 's/@IFIT_VERSION@/'$IFIT_VERSION'/'  $file     > $file.tmp
sed 's/@IFIT_NAME@/'$IFIT_NAME'/'        $file.tmp > $file
sed 's/@IFIT_TARNAME@/'$IFIT_TARNAME'/'  $file     > $file.tmp
sed 's/@IFIT_DATE@/'$MONTH'. '$DAY', '$YEAR'/'  $file.tmp > $file
rm $file.tmp
done

cd $TMPDIR
# Create tar archive SRC
zip -r $PW/../$IFIT_TARNAME-$IFIT_VERSION-src.zip $IFIT_TARNAME-$IFIT_VERSION

if [ -x `which mcc` ]
then
  echo create the standalone version into $TMPDIR/$IFIT_TARNAME-$IFIT_VERSION-amd64
  cd $IFIT_TARNAME-$IFIT_VERSION/Applications/GUI/standalone
  ./make.sh $TMPDIR/$IFIT_TARNAME-$IFIT_VERSION-amd64
  cd $TMPDIR
fi

if [ -e $TMPDIR/$IFIT_TARNAME-$IFIT_VERSION-amd64 ]
then
  if [ -e /etc/debian_version ]
  then
    if [ -e build-chroot-amd64 ]
    then
      echo Proceeding to amd64 .deb build from $TMPDIR/$IFIT_TARNAME-$IFIT_VERSION-amd64
      # First, clean up in case of previous iFit installs in the chrooot
      sudo rm -f  build-chroot-amd64/usr/local/bin/*
      sudo rm -rf build-chroot-amd64/usr/local/ifit
      echo install amd64 mex distribution in /root
      sudo cp $IFIT_TARNAME-$IFIT_VERSION/Applications/GUI/standalone/deb/debcreate build-chroot-amd64/root
      sudo cp -rf $IFIT_TARNAME-$IFIT_VERSION-amd64 build-chroot-amd64/root
      sudo cp -rf $IFIT_TARNAME-$IFIT_VERSION build-chroot-amd64/root
      sudo mkdir  build-chroot-amd64/build
      sudo chroot build-chroot-amd64 apt-get update
      sudo chmod u+x build-chroot-amd64/root/debcreate
      sudo chroot build-chroot-amd64   /root/debcreate $1 amd64
      echo
      echo
      echo Build packages created:
      echo
      cp build-chroot-amd64/build/*deb .
      ls -lf $IFIT_TARNAME-$IFIT_VERSION*.* $IFIT_TARNAME-$IFIT_VERSION*.*
      echo
    else
      echo You need a chroot environment based on debootstrap in build-chroot-amd64 before building the amd64 deb package - create using something like
      echo sudo debootstrap --arch amd64 precise build-chroot-amd64
    fi # build chroot present
  fi # debian
fi # amd64 build

echo "========================================================================="
echo "mkdist: Distro creation for $IFIT_STRING"
echo Your $IFIT_STRING dist packages are placed in
echo ../$IFIT_TARNAME-$IFIT_VERSION-src.zip

