#!/bin/sh
# debcreate <version> <arch>

export BUILDDIR="/build/@IFIT_TARNAME@-@IFIT_VERSION@"

echo Performing @IFIT_TARNAME@-@IFIT_VERSION@ install to ${BUILDDIR}/usr/local

PW=`pwd`
cd    ${BUILDDIR}/usr/local/bin
rm -f ${BUILDDIR}/usr/local/bin/ifit
ln -s ../ifit/ifit .
cd $PW

echo create the DEB build directory
sed -i "s/arch/$2/g" ${BUILDDIR}/DEBIAN/control

find ${BUILDDIR} -type d -exec chmod 0755 \{\} \;

dpkg-deb --build ${BUILDDIR}

mv /build/@IFIT_TARNAME@-@IFIT_VERSION@.deb \
                                     /build/@IFIT_TARNAME@-@IFIT_VERSION@-$2.deb

# rm -rf $BUILDDIR


