function mifit_Data_Math_Binary(varargin)
% Data/Transform binary: apply a binary operator on Datasets
  
  op = {'cat 1 (on 1st axis)','cat 2 (on 2nd axis)','cat 3 (on 3rd axis)', ...
  'combine (merge)','conv (convolve)','convn (convolution, normalised)', ...
  'eq (equal ==)','ge (greater or equal >=)','gt (greater >)','le (lower or equal <=)', ...
  'lt (lower <)','minus (-)', ...
  'mrdivide (matrix division /)','ne (not equal)','plus (addition +)','power (power ^)', ...
  'rdivide (division ./)','times (multiplication) *','xcorr (cross correlation)', ...
  'interp (interpolation)'};
  
  mifit_Data_Operator(op);
