function mifit_File_Reset(varargin)
% File/Reset: clear data sets, user models and Preferences
  options.Default     = 'Cancel';
  options.Interpreter = 'tex';
  ButtonName = questdlg({ ...
    '{\fontsize{14}{\color{blue}Reset default configuration ?}}', ...
    'Selecting "RESET" clears the Data set list, History and the Log file.', ...
    'Selecting "FACTORY settings" also resets the Models and Preferences in', ...
    prefdir, ...
    'FACTORY reset requires to quit and restart miFit', ...
    '{\bf{Reset now ?}}'}, 'miFit: Reset ?', ...
    'Reset', 'Cancel', 'Factory settings', ...
    options);
  if ~strcmpi(ButtonName, 'Cancel')
    mifit_File_Reset_Factory(ButtonName);
    
    if ~strcmpi(ButtonName, 'Reset') % Factory settings
      mifit_File_Exit;
      mifit;
    end
  end
