function mifit_Data_Math_Unary(varargin)
% Data/Transform unary: apply a unary operator on Datasets
  
  op = {'abs','acosh','acos','asinh','asin','atanh','atan','ceil (upper integer)', ...
    'conj (conjugate)','cosh','cos', ...
    'ctranspose (conjugate transpose)','exp','fliplr (left-right mirror)', ...
    'flipud (up-down mirror)','floor (lowest integer)','full (expand matrices)', ...
    'imag (imaginary part)','isfinite (where not NaN or Inf)', ...
    'isfloat','isinf (where is Inf)','isinteger','islogical','isnan (where is nan)', ...
    'isnumeric','isreal','isscalar', ...
    'issparse','log10','log','norm (norm-2)','not','pack (compress data set)', ...
    'real (real part)','round (nearest integer)','sign','sinh','sin', ...
    'sparse (convert to sparse matrices)','sqrt','tanh','tan','transpose', ...
    'uminus (-)', 'fill (fill missing data)', ...
    'min (minimum value)','mean (mean value)','median (median value)',...
    'max (maximum value)', ...
    'sort (sort rows)','squeeze (remove singleton dimensions)',...
    'double (convert to double array)','logical','single','sqr (square ^2)', ...
    'imroi (select ROI)'};
  
  mifit_Data_Operator(op);
